### PR TITLE
New Logo

### PR DESCRIPTION
**Pull request by anilkilic**
Folder contains 1024px, 768px, 512px transparent png files with editable svg file.

### CODE REVIEW

**Comment by CodeMan99** [comment]
Thanks for all this work.

One last request if I may? Could we please do a black background at 70% opacity?

**Comment by anilkilic** [comment]
Sure thing. 
I couldn't be sure about how to add commit to PR, so here are the files. Hope those are what you are looking for.
[with_background.zip](https://github.com/CodeMan99/blitzbot/files/1978073/with_background.zip)

**Comment by CodeMan99** [comment]
@anilkilic It's just a matter of overwriting the files in the same location/directory, then `git add logos` & `git commit`. I'll handle it for you though. No big deal.

**Comment by CodeMan99** [comment]
@anilkilic Thanks again for implementing the new logo! Not really sure when the logo will go live. Updating the avatar for discord is a PITA :(

**Pull request merged**
