### PR TITLE
Forked Blitzbot for EU server.

### PR DESCRIPTION
**Pull request by ArMikael**
Added region property for EU server in bot.js

### CODE REVIEW

**Comment by CodeMan99** [comment]
This is correct. Not going to merge it as I was suggesting you push the fork so that I can help make sure your instance is up-to-date.

FYI: I am currently working on changes to [wotblitz](//github.com/CodeMan99/wotblitz.js) to allow supporting multiple regions in the same codebase.

**Comment by ArMikael** [comment]
@CodeMan99 that's will be nice. Do you think about adding new features to the bot? Do you have time for this? I can purpose some ideas if you are still interested in this project.

**Comment by CodeMan99** [comment]
Yup. View my tickets #2, #3, & #4. The progress is slow because I generally only work on the project during the weekend.

**Comment by CodeMan99** [comment]
@ArMikael Multi-region support inbound! 82e3f57a1eb2dc84b8a7ffa57c0561f63de09a84

**Comment by DaanLoman** [comment]
how do i change the NA server to EU on discord?

**Pull request closed without merging**
